import { z } from "zod";
import { ToolAnnotations } from "@modelcontextprotocol/sdk/types.js";
import {
  createTranslationKeyBulkParameters,
  updateTranslationsBulkParameters,
  getAllTranslationKeysParameters,
  getTranslationKeyDetailsParameters,
  getTagsParameters,
  createTagParameters,
  getLanguagesParameters,
  getTranslationsParameters,
  createLanguageParameters,
  getEnvironmentsParameters,
  getEnvironmentDetailsParameters,
  publishTranslationsParameters,
  updateTranslationKeyParameters,
  deleteTranslationKeysBulkParameters,
  createEnvironmentParameters,
  getTranslationKeysParameters,
  createTranslationKeyParameters,
  deleteTranslationKeyParameters,
  updateTranslationKeyByIdParameters,
  getAllTranslationKeysV2Parameters,
  uploadTranslationKeyScreenshotParameters,
  uploadTranslationKeyScreenshotFileParameters,
  uploadTranslationKeyScreenshotsBulkParameters,
  updateTranslationParameters,
  updateTagParameters,
  deleteTagParameters,
  getLanguageParameters,
  updateLanguageParameters,
  deleteLanguageParameters,
  getFileFormatsParameters,
  getCustomersParameters,
  createCustomerParameters,
  getCustomerParameters,
  updateCustomerParameters,
  deleteCustomerParameters,
  autoTranslateTextParameters,
  createAutoTranslationJobsParameters,
  getAutoTranslationJobsParameters,
  getAutoTranslationJobParameters,
  importTranslationsParameters,
  exportTranslationsParameters,
  getActivityParameters,
  getActivityChangesParameters,
  getProjectDetailsParameters,
  getGlossaryEntriesParameters,
  createGlossaryEntryParameters,
  deleteGlossaryEntryParameters,
} from "./parameters.js";
import {
  createTranslationKeyPrompt,
  updateTranslationsBulkPrompt,
  getAllTranslationKeysPrompt,
  getTranslationKeyDetailsPrompt,
  getTagsPrompt,
  createTagPrompt,
  getLanguagesPrompt,
  getTranslationsPrompt,
  createLanguagePrompt,
  getEnvironmentsPrompt,
  getEnvironmentDetailsPrompt,
  publishTranslationsPrompt,
  updateTranslationKeyPrompt,
  deleteTranslationKeysBulkPrompt,
  createEnvironmentPrompt,
  getTranslationKeysPrompt,
  createTranslationKeyPromptSingle,
  deleteTranslationKeyPrompt,
  updateTranslationKeyByIdPrompt,
  getAllTranslationKeysV2Prompt,
  uploadTranslationKeyScreenshotPrompt,
  uploadTranslationKeyScreenshotFilePrompt,
  uploadTranslationKeyScreenshotsBulkPrompt,
  updateTranslationPrompt,
  updateTagPrompt,
  deleteTagPrompt,
  getLanguagePrompt,
  updateLanguagePrompt,
  deleteLanguagePrompt,
  getCustomersPrompt,
  createCustomerPrompt,
  getCustomerPrompt,
  updateCustomerPrompt,
  deleteCustomerPrompt,
  autoTranslateTextPrompt,
  createAutoTranslationJobsPrompt,
  getAutoTranslationJobsPrompt,
  getAutoTranslationJobPrompt,
  importTranslationsPrompt,
  exportTranslationsPrompt,
  getFileFormatsPrompt,
  getActivityPrompt,
  getActivityChangesPrompt,
  getProjectDetailsPrompt,
  getGlossaryEntriesPrompt,
  createGlossaryEntryPrompt,
  deleteGlossaryEntryPrompt,
} from "./prompts.js";

export type Tool = {
  method: string;
  name: string;
  description: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  parameters: z.ZodObject<any, any, any, any>;
  annotations: ToolAnnotations;
};

const readOnly: ToolAnnotations = {
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: true,
};

const createOrUpdate: ToolAnnotations = {
  readOnlyHint: false,
  destructiveHint: false,
  idempotentHint: false,
  openWorldHint: true,
};

const destructive: ToolAnnotations = {
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: false,
  openWorldHint: true,
};

const tools: Tool[] = [
  {
    method: "create_translation_key_bulk",
    name: "Create Translation Key Bulk",
    description: createTranslationKeyPrompt,
    parameters: createTranslationKeyBulkParameters,
    annotations: createOrUpdate,
  },
  {
    method: "update_translations_bulk",
    name: "Update Translations Bulk",
    description: updateTranslationsBulkPrompt,
    parameters: updateTranslationsBulkParameters,
    annotations: createOrUpdate,
  },
  {
    method: "get_all_translation_keys",
    name: "Get All Translation Keys",
    description: getAllTranslationKeysPrompt,
    parameters: getAllTranslationKeysParameters,
    annotations: readOnly,
  },
  {
    method: "get_translation_key_details",
    name: "Get Translation Key Details",
    description: getTranslationKeyDetailsPrompt,
    parameters: getTranslationKeyDetailsParameters,
    annotations: readOnly,
  },
  {
    method: "get_tags",
    name: "Get Tags",
    description: getTagsPrompt,
    parameters: getTagsParameters,
    annotations: readOnly,
  },
  {
    method: "create_tag",
    name: "Create Tag",
    description: createTagPrompt,
    parameters: createTagParameters,
    annotations: createOrUpdate,
  },
  {
    method: "get_languages",
    name: "Get Languages",
    description: getLanguagesPrompt,
    parameters: getLanguagesParameters,
    annotations: readOnly,
  },
  {
    method: "create_language",
    name: "Create Language",
    description: createLanguagePrompt,
    parameters: createLanguageParameters,
    annotations: createOrUpdate,
  },
  {
    method: "get_translations",
    name: "Get Translations",
    description: getTranslationsPrompt,
    parameters: getTranslationsParameters,
    annotations: readOnly,
  },
  {
    method: "update_translation_key",
    name: "Update Translation Key",
    description: updateTranslationKeyPrompt,
    parameters: updateTranslationKeyParameters,
    annotations: createOrUpdate,
  },
  {
    method: "delete_translation_keys_bulk",
    name: "Delete Translation Keys Bulk",
    description: deleteTranslationKeysBulkPrompt,
    parameters: deleteTranslationKeysBulkParameters,
    annotations: destructive,
  },
  {
    method: "get_environments",
    name: "Get Environments",
    description: getEnvironmentsPrompt,
    parameters: getEnvironmentsParameters,
    annotations: readOnly,
  },
  {
    method: "get_environment_details",
    name: "Get Environment Details",
    description: getEnvironmentDetailsPrompt,
    parameters: getEnvironmentDetailsParameters,
    annotations: readOnly,
  },
  {
    method: "publish_translations",
    name: "Publish Translations",
    description: publishTranslationsPrompt,
    parameters: publishTranslationsParameters,
    annotations: destructive,
  },
  {
    method: "create_environment",
    name: "Create Environment",
    description: createEnvironmentPrompt,
    parameters: createEnvironmentParameters,
    annotations: createOrUpdate,
  },
  {
    method: "get_translation_keys",
    name: "Get Translation Keys",
    description: getTranslationKeysPrompt,
    parameters: getTranslationKeysParameters,
    annotations: readOnly,
  },
  {
    method: "create_translation_key",
    name: "Create Translation Key",
    description: createTranslationKeyPromptSingle,
    parameters: createTranslationKeyParameters,
    annotations: createOrUpdate,
  },
  {
    method: "delete_translation_key",
    name: "Delete Translation Key",
    description: deleteTranslationKeyPrompt,
    parameters: deleteTranslationKeyParameters,
    annotations: destructive,
  },
  {
    method: "update_translation_key_by_id",
    name: "Update Translation Key By Id",
    description: updateTranslationKeyByIdPrompt,
    parameters: updateTranslationKeyByIdParameters,
    annotations: createOrUpdate,
  },
  {
    method: "get_all_translation_keys_v2",
    name: "Get All Translation Keys V2",
    description: getAllTranslationKeysV2Prompt,
    parameters: getAllTranslationKeysV2Parameters,
    annotations: readOnly,
  },
  {
    method: "upload_translation_key_screenshot",
    name: "Upload Translation Key Screenshot",
    description: uploadTranslationKeyScreenshotPrompt,
    parameters: uploadTranslationKeyScreenshotParameters,
    annotations: createOrUpdate,
  },
  {
    method: "upload_translation_key_screenshot_file",
    name: "Upload Translation Key Screenshot File",
    description: uploadTranslationKeyScreenshotFilePrompt,
    parameters: uploadTranslationKeyScreenshotFileParameters,
    annotations: createOrUpdate,
  },
  {
    method: "upload_translation_key_screenshots_bulk",
    name: "Upload Translation Key Screenshots Bulk",
    description: uploadTranslationKeyScreenshotsBulkPrompt,
    parameters: uploadTranslationKeyScreenshotsBulkParameters,
    annotations: createOrUpdate,
  },
  {
    method: "update_translation",
    name: "Update Translation",
    description: updateTranslationPrompt,
    parameters: updateTranslationParameters,
    annotations: createOrUpdate,
  },
  {
    method: "update_tag",
    name: "Update Tag",
    description: updateTagPrompt,
    parameters: updateTagParameters,
    annotations: createOrUpdate,
  },
  {
    method: "delete_tag",
    name: "Delete Tag",
    description: deleteTagPrompt,
    parameters: deleteTagParameters,
    annotations: destructive,
  },
  {
    method: "get_language",
    name: "Get Language",
    description: getLanguagePrompt,
    parameters: getLanguageParameters,
    annotations: readOnly,
  },
  {
    method: "update_language",
    name: "Update Language",
    description: updateLanguagePrompt,
    parameters: updateLanguageParameters,
    annotations: createOrUpdate,
  },
  {
    method: "delete_language",
    name: "Delete Language",
    description: deleteLanguagePrompt,
    parameters: deleteLanguageParameters,
    annotations: destructive,
  },
  {
    method: "get_customers",
    name: "Get Customers",
    description: getCustomersPrompt,
    parameters: getCustomersParameters,
    annotations: readOnly,
  },
  {
    method: "create_customer",
    name: "Create Customer",
    description: createCustomerPrompt,
    parameters: createCustomerParameters,
    annotations: createOrUpdate,
  },
  {
    method: "get_customer",
    name: "Get Customer",
    description: getCustomerPrompt,
    parameters: getCustomerParameters,
    annotations: readOnly,
  },
  {
    method: "update_customer",
    name: "Update Customer",
    description: updateCustomerPrompt,
    parameters: updateCustomerParameters,
    annotations: createOrUpdate,
  },
  {
    method: "delete_customer",
    name: "Delete Customer",
    description: deleteCustomerPrompt,
    parameters: deleteCustomerParameters,
    annotations: destructive,
  },
  {
    method: "auto_translate_text",
    name: "Auto-translate Text",
    description: autoTranslateTextPrompt,
    parameters: autoTranslateTextParameters,
    annotations: createOrUpdate,
  },
  {
    method: "create_auto_translation_jobs",
    name: "Create Auto-translation Jobs",
    description: createAutoTranslationJobsPrompt,
    parameters: createAutoTranslationJobsParameters,
    annotations: createOrUpdate,
  },
  {
    method: "get_auto_translation_jobs",
    name: "Get Auto-translation Jobs",
    description: getAutoTranslationJobsPrompt,
    parameters: getAutoTranslationJobsParameters,
    annotations: readOnly,
  },
  {
    method: "get_auto_translation_job",
    name: "Get Auto-translation Job",
    description: getAutoTranslationJobPrompt,
    parameters: getAutoTranslationJobParameters,
    annotations: readOnly,
  },
  {
    method: "import_translations",
    name: "Import Translations",
    description: importTranslationsPrompt,
    parameters: importTranslationsParameters,
    annotations: createOrUpdate,
  },
  {
    method: "export_translations",
    name: "Export Translations",
    description: exportTranslationsPrompt,
    parameters: exportTranslationsParameters,
    annotations: readOnly,
  },
  {
    method: "get_file_formats",
    name: "Get File Formats",
    description: getFileFormatsPrompt,
    parameters: getFileFormatsParameters,
    annotations: readOnly,
  },
  {
    method: "get_activity",
    name: "Get Activity",
    description: getActivityPrompt,
    parameters: getActivityParameters,
    annotations: readOnly,
  },
  {
    method: "get_activity_changes",
    name: "Get Activity Changes",
    description: getActivityChangesPrompt,
    parameters: getActivityChangesParameters,
    annotations: readOnly,
  },
  {
    method: "get_project_details",
    name: "Get Project Details",
    description: getProjectDetailsPrompt,
    parameters: getProjectDetailsParameters,
    annotations: readOnly,
  },
  {
    method: "get_glossary_entries",
    name: "Get Glossary Entries",
    description: getGlossaryEntriesPrompt,
    parameters: getGlossaryEntriesParameters,
    annotations: readOnly,
  },
  {
    method: "create_glossary_entry",
    name: "Create Glossary Entry",
    description: createGlossaryEntryPrompt,
    parameters: createGlossaryEntryParameters,
    annotations: createOrUpdate,
  },
  {
    method: "delete_glossary_entry",
    name: "Delete Glossary Entry",
    description: deleteGlossaryEntryPrompt,
    parameters: deleteGlossaryEntryParameters,
    annotations: destructive,
  },
];

export default tools;
